income<-read.csv("C:/Users/lk21001206/Desktop/R Lectures/income.data.csv")
head(income)
str(income)
income$X<-as.factor(income$X)
head(income)
is.data.frame(income)
is.vector(income)
income$X<-as.numeric(income$X)
colMeans(income$income)
library(readr)
library(ggplot2)
data("mpg")
head(mpg)
mpg[,c(1,4,7)]
plot(income$income,income$happiness)
cor(income$income,income$happiness)
hist(income$happiness)
